/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql_estetica;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class Pedidos extends javax.swing.JFrame {
MySQL db = new MySQL();
    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        mostrartabla();
    }
    void mostrartabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Pedidos");
        modelo.addColumn("ID Cliente");
        modelo.addColumn("ID Productos");
        modelo.addColumn("ID Empleados");
        modelo.addColumn("Fecha");
        modelo.addColumn("Piezas");
        modelo.addColumn("Total");
        modelo.addColumn("Precio");
        Tabla2.setModel(modelo);
        
        String sql= "SELECT * FROM pedidos";
        
        String datos[]= new String [8];
        Statement st;
        
        try{
            st=MySQL.Conexion.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                modelo.addRow(datos);
            }
            Tabla2.setModel(modelo);
        }catch(SQLException ex){
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        JLabel6 = new javax.swing.JLabel();
        JLabel7 = new javax.swing.JLabel();
        JLabel8 = new javax.swing.JLabel();
        JLabel9 = new javax.swing.JLabel();
        Titulo5 = new javax.swing.JLabel();
        ID_Pedidos = new javax.swing.JTextField();
        ID_Clientes2 = new javax.swing.JTextField();
        ID_Productos2 = new javax.swing.JTextField();
        ID_Empleados2 = new javax.swing.JTextField();
        Fecha2 = new javax.swing.JTextField();
        Piezas = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Precio_Total = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        Aceptar3 = new javax.swing.JButton();
        Cancelar3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N

        JLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel1.setText("ID");

        JLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel2.setText("ID de Cliente");

        JLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel3.setText("ID de Producto");

        JLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel4.setText("ID de Empleados");

        JLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel5.setText("Fecha");

        JLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel6.setText("Piezas");

        JLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel7.setText("Total");

        JLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel8.setText("Forma de Pago");

        JLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel9.setText("Precio Total");

        Titulo5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo5.setForeground(new java.awt.Color(255, 255, 255));
        Titulo5.setText("Pedidos");

        ID_Pedidos.setFocusCycleRoot(true);
        ID_Pedidos.setName(""); // NOI18N

        ID_Clientes2.setFocusCycleRoot(true);
        ID_Clientes2.setName(""); // NOI18N
        ID_Clientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_Clientes2ActionPerformed(evt);
            }
        });

        ID_Productos2.setFocusCycleRoot(true);
        ID_Productos2.setName(""); // NOI18N

        ID_Empleados2.setFocusCycleRoot(true);
        ID_Empleados2.setName(""); // NOI18N
        ID_Empleados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_Empleados2ActionPerformed(evt);
            }
        });

        Fecha2.setFocusCycleRoot(true);
        Fecha2.setName(""); // NOI18N

        Piezas.setFocusCycleRoot(true);
        Piezas.setName(""); // NOI18N
        Piezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiezasActionPerformed(evt);
            }
        });

        Total.setFocusCycleRoot(true);
        Total.setName(""); // NOI18N

        Precio_Total.setFocusCycleRoot(true);
        Precio_Total.setName(""); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Tarjeta", " " }));

        Aceptar3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Aceptar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783341_Check.png"))); // NOI18N
        Aceptar3.setText("Aceptar");
        Aceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar3ActionPerformed(evt);
            }
        });

        Cancelar3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cancelar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783448_delete.png"))); // NOI18N
        Cancelar3.setText("Cancelar");
        Cancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783523_icontexto-aurora-folders-contacts.png"))); // NOI18N
        jButton1.setText("Obtener Registros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783602_Remove-Male-User.png"))); // NOI18N
        jButton2.setText("Borrar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pinceles-de-maquillaje-de-lana-herramientas-Kit-profesional-10-unids-estética-Facial-maquillaje-cepillo-conjunto.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(Titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(ID_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(ID_Productos2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel6)
                .addGap(86, 86, 86)
                .addComponent(Piezas, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel7))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(JLabel9)
                .addGap(18, 18, 18)
                .addComponent(Precio_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(Aceptar3)
                .addGap(18, 18, 18)
                .addComponent(Cancelar3))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(604, 604, 604)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(ID_Empleados2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel8))
            .addGroup(layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(ID_Clientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(JLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo5)
                .addGap(6, 6, 6)
                .addComponent(ID_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(JLabel2)
                .addGap(20, 20, 20)
                .addComponent(ID_Productos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JLabel6))
                    .addComponent(Piezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(JLabel7)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JLabel9))
                    .addComponent(Precio_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Aceptar3)
                    .addComponent(Cancelar3)))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(ID_Empleados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(JLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(JLabel8))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(JLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ID_Clientes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(JLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(JLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ID_Clientes2.getAccessibleContext().setAccessibleName("");
        ID_Productos2.getAccessibleContext().setAccessibleName("");
        ID_Empleados2.getAccessibleContext().setAccessibleName("");
        Fecha2.getAccessibleContext().setAccessibleName("");
        Piezas.getAccessibleContext().setAccessibleName("");
        Total.getAccessibleContext().setAccessibleName("");
        Precio_Total.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Aceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar3ActionPerformed
        db.MySQLConnection("root", "", "mydb");
        db.insertDatapedidos("Pedidos",
                ID_Pedidos.getText(),
                ID_Clientes2.getText(),
                ID_Productos2.getText(),
                ID_Empleados2.getText(),
                Fecha2.getText(),
                Piezas.getText(),
                Total.getText(),
                Precio_Total.getText(),
                jComboBox1.getSelectedItem().toString());
        this.dispose();
    }//GEN-LAST:event_Aceptar3ActionPerformed

    private void Cancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db.MySQLConnection("root", "", "mydb");
        db.getValuesPedidos("Pedidos");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BorrarPedidos bc=new BorrarPedidos();
        bc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiezasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PiezasActionPerformed

    private void ID_Clientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_Clientes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_Clientes2ActionPerformed

    private void ID_Empleados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_Empleados2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_Empleados2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar3;
    private javax.swing.JButton Cancelar3;
    private javax.swing.JTextField Fecha2;
    private javax.swing.JTextField ID_Clientes2;
    private javax.swing.JTextField ID_Empleados2;
    private javax.swing.JTextField ID_Pedidos;
    private javax.swing.JTextField ID_Productos2;
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel JLabel6;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JLabel JLabel8;
    private javax.swing.JLabel JLabel9;
    private javax.swing.JTextField Piezas;
    private javax.swing.JTextField Precio_Total;
    private javax.swing.JTable Tabla2;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JTextField Total;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
