/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql_estetica;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCxxCC1
 */
public class Productos extends javax.swing.JFrame {
MySQL db = new MySQL();
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        mostrartabla();
    }
    void mostrartabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Productos");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Existencia");
        modelo.addColumn("Fecha");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("ID Provedor");
        Tabla3.setModel(modelo);
        
        String sql= "SELECT * FROM productos";
        
        String datos[]= new String [9];
        Statement st;
        
        try{
            st=MySQL.Conexion.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                modelo.addRow(datos);
            }
            Tabla3.setModel(modelo);
        }catch(SQLException ex){
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        JLabel6 = new javax.swing.JLabel();
        JLabel7 = new javax.swing.JLabel();
        JLabel8 = new javax.swing.JLabel();
        Titulo4 = new javax.swing.JLabel();
        ID_Productos = new javax.swing.JTextField();
        Nombre_Prod = new javax.swing.JTextField();
        Precio_Prod = new javax.swing.JTextField();
        Existencia_Prod = new javax.swing.JTextField();
        FechaCaducidad_Prod = new javax.swing.JTextField();
        Descripcion_Prod = new javax.swing.JTextField();
        Precio_Producto = new javax.swing.JTextField();
        ID_Provedores = new javax.swing.JTextField();
        Aceptar4 = new javax.swing.JButton();
        Cancelar4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jonathan\\Documents\\Tercer Parcial\\Proyecto Base y Progra\\Imagenes\\6866703-hd-makeup-wallpaper.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel1.setText("ID");

        JLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel2.setText("Nombre");

        JLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel3.setText("Precio");

        JLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel4.setText("Existencia");

        JLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel5.setText("Fecha");

        JLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel6.setText("Descripcion");

        JLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel7.setText("Precio");

        JLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabel8.setText("ID de Provedor");

        Titulo4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(255, 255, 255));
        Titulo4.setText("Productos");

        ID_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_ProductosActionPerformed(evt);
            }
        });

        Nombre_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_ProdActionPerformed(evt);
            }
        });

        Precio_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_ProdActionPerformed(evt);
            }
        });

        Aceptar4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Aceptar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783341_Check.png"))); // NOI18N
        Aceptar4.setText("Aceptar");
        Aceptar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar4ActionPerformed(evt);
            }
        });

        Cancelar4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cancelar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783448_delete.png"))); // NOI18N
        Cancelar4.setText("Cancelar");
        Cancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783523_icontexto-aurora-folders-contacts.png"))); // NOI18N
        jButton1.setText("Obtener Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1448783602_Remove-Male-User.png"))); // NOI18N
        jButton2.setText("Borrar  Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/women-jennifer-lopez-curly-hair-HD-Wallpapers.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(Titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel1)
                .addGap(110, 110, 110)
                .addComponent(ID_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel2)
                .addGap(69, 69, 69)
                .addComponent(Nombre_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(Precio_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel4)
                .addGap(52, 52, 52)
                .addComponent(Existencia_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel5)
                .addGap(81, 81, 81)
                .addComponent(FechaCaducidad_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel6)
                .addGap(40, 40, 40)
                .addComponent(Descripcion_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel7)
                .addGap(79, 79, 79)
                .addComponent(Precio_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel8))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Aceptar4)
                .addGap(18, 18, 18)
                .addComponent(Cancelar4)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ID_Provedores, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Titulo4)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLabel1))
                    .addComponent(ID_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLabel2))
                    .addComponent(Nombre_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Precio_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLabel4))
                    .addComponent(Existencia_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLabel5))
                    .addComponent(FechaCaducidad_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLabel6))
                    .addComponent(Descripcion_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLabel7))
                    .addComponent(Precio_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(JLabel8)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Aceptar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(JLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(ID_Provedores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_ProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_ProdActionPerformed

    private void Precio_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_ProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_ProdActionPerformed

    private void Aceptar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar4ActionPerformed
        MySQL db = new MySQL();
        db.MySQLConnection("root", "", "mydb");
        db.insertDataproductos("Productos", 
                ID_Productos.getText(),
                Nombre_Prod.getText(),
                Precio_Prod.getText(),
                Existencia_Prod.getText(),
                FechaCaducidad_Prod.getText(),
                Descripcion_Prod.getText(),
                Precio_Producto.getText(),
                ID_Provedores.getText());
        this.dispose();
    }//GEN-LAST:event_Aceptar4ActionPerformed

    private void Cancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar4ActionPerformed

    private void ID_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_ProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db.MySQLConnection("root", "", "mydb");
        db.getValuesProductos("Productos");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BorrarProductos bc=new BorrarProductos();
        bc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar4;
    private javax.swing.JButton Cancelar4;
    private javax.swing.JTextField Descripcion_Prod;
    private javax.swing.JTextField Existencia_Prod;
    private javax.swing.JTextField FechaCaducidad_Prod;
    private javax.swing.JTextField ID_Productos;
    private javax.swing.JTextField ID_Provedores;
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel JLabel6;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JLabel JLabel8;
    private javax.swing.JTextField Nombre_Prod;
    private javax.swing.JTextField Precio_Prod;
    private javax.swing.JTextField Precio_Producto;
    private javax.swing.JTable Tabla3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
